version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.4
    container_name: parking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parking
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

  backend:
    build:
      context: ./backend
    container_name: parking_api
    env_file: .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./data:/data:ro
    depends_on:
      - db
    ports:
      - "8000:8000"
